options:
    assets: site/assets
    bower: assets/bower_components
    engine: handlebars
    data: config/*.yml
    layoutdir: src/templates/layouts
    helpers:
        - handlebars-helper-compose
        - helper-moment
site:
    options:
        ext: .html
        layout: page.hbs
        flatten: true
        content:
            blog: src/content/blog/**.md
            work: src/content/work/**.md
    files: 
        "site/": 
            - src/**.hbs
            - src/**.md 

