### Content Sources
src:
    # ---------------------------------------------------------------------- 
    github:         
        url:            https://github.com/manleyjster.private.actor.atom?token=<%= secret.github.token %>
        importance: 
            1: 
                - issues
                - gist
                - deployment
                - pullrequest
                - pullrequestreviewcomment
                - issuecomment
                - release
                - teamadd
                - push
    # ---------------------------------------------------------------------- 
    outoftheyards:  
        url:            http://www.outoftheyards.com/feed/atom/
        importance:     5
    # ---------------------------------------------------------------------- 
    publiclab:
        url:            http://publiclab.org/feed/justinmanley.rss
        importance:     4
    # ---------------------------------------------------------------------- 

### Output Types
dest:
    event:      src/content/feeds/feed.html
    article:    src/content/feeds/article.html
    archive:    src/content/feeds/archive.html