src:
    github:         https://github.com/manleyjster.private.actor.atom?token=f6728524d3835a2cd3180dab9b758497
    outoftheyards:  http://www.outoftheyards.com/feed/atom/
    publiclab:      http://publiclab.org/feed/justinmanley.rss
dest: 
    event: src/feeds/feed.html
    article: src/feeds/article.html
    archive: src/feeds/archive.html