# Shortcuts for static assets
css:
    octicons:           bower_components/octicons/octicons/octicons.css
    bootstrap:          bower_components/bootstrap/dist/css/bootstrap.min.css
    bootstrapTheme:     bower_components/bootstrap/dist/css/bootstrap-theme.css
    fontAwesome:        bower_components/font-awesome/css/font-awesome.min.css
    highlightTheme:     bower_components/highlightjs/styles/paraiso.light.css
js: 
    jquery:             bower_components/jquery/dist/jquery.min.js
    bootstrap:          bower_components/bootstrap/dist/js/bootstrap.min.js
    socket:             bower_components/socket-io-client/socket.io.js
    highlight:          bower_components/highlightjs/highlight.pack.js
