#!/bin/sh

# Usage: 
# ./github <number of updates>

# Example:
# ./github 5

events="Issues|Push|CommitComment|Create|Gist|IssueComment|PullRequest|ReleaseEvent"

xsltproc --stringparam predicate $events scripts/xslt/github-prune.xslt data/raw/github.xml \
	| xsltproc --stringparam num $1 scripts/xslt/github-limit.xslt - \
	| sed 's/&lt;/</g' \
	| sed 's/&gt;/>/g' \
	> data/feeds/github.xml