#!/bin/sh

# Usage: 
# scripts/publiclab

data=`curl http://publiclab.org/feed/justinmanley.rss`

echo $data \
	| scripts/js/publiclab.js \
	> data/feeds/publiclab.html

echo $data > data/cached/publiclab.xml